site_name: tdfpy
site_description: A Python library for parsing Bruker timsTOF data with centroiding and noise filtering.
repo_url: https://github.com/tacular-omics/tdfpy
repo_name: tacular-omics/tdfpy
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - Readers: api/readers.md
    - Frames: api/frames.md
    - Precursor: api/precursor.md
    - DIA Windows: api/windows.md
    - Metadata: api/metadata.md
    - Lookups: api/lookup.md
    - Centroiding: api/centroiding.md
    - PandasTDF: api/low-level.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: True
            show_symbol_type_heading: true
            members_order: source
            inherited_members: true
            merge_init_into_class: true
            filters: ["!^_"]
            show_signature_annotations: true
            separate_signature: true
            annotations_path: source
            signature_crossrefs: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
